// Generated by CoffeeScript 1.6.3
(function() {
  var coffee, concat, connect, gulp, gutil, http, path, sass;

  gulp = require('gulp');

  gutil = require('gulp-util');

  coffee = require('gulp-coffee');

  concat = require('gulp-concat');

  sass = require('gulp-sass');

  connect = require('connect');

  http = require('http');

  path = require('path');

  gulp.task('webserver', function() {
    var app, base, directory, hostname, port;
    port = 3000;
    hostname = null;
    base = path.resolve('./dist');
    directory = path.resolve('./dist');
    app = connect().use(connect["static"](base)).use(connect.directory(directory));
    return http.createServer(app).listen(port, hostname);
  });

  gulp.task('scripts', function() {
    return gulp.src('app/**/*.coffee').pipe(concat('app.coffee')).pipe(coffee()).pipe(gulp.dest('dist'));
  });

  gulp.task('styles', function() {
    return gulp.src('app/app.scss').pipe(sass({
      includePaths: ['app']
    })).pipe(concat('app.css')).pipe(gulp.dest('dist'));
  });

  gulp.task('default', function() {
    gulp.run('webserver', 'scripts', 'styles');
    gulp.watch('app/**/*.coffee', function() {
      return gulp.run('scripts');
    });
    return gulp.watch('app/**/*.scss', function() {
      return gulp.run('styles');
    });
  });

}).call(this);
